version: '3.7'

services:
  rl_coach:
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [node.labels.Sagemaker == true ]
  robomaker:
    deploy:
      restart_policy:
        condition: none
      replicas: ${DR_WORKERS}
      placement:
        constraints: [node.labels.Robomaker == true ]
    environment:
        - DOCKER_REPLICA_SLOT={{.Task.Slot}}