version: "3.7"

networks:
  default:
    external: true
    name: sagemaker-local

services:
  rl_coach:
    image: awsdeepracercommunity/deepracer-rlcoach:${DR_COACH_IMAGE}
    environment:
      - AWS_REGION=${DR_AWS_APP_REGION}
      - SAGEMAKER_IMAGE=${DR_SAGEMAKER_IMAGE}
      - PRETRAINED=${DR_LOCAL_S3_PRETRAINED}
      - PRETRAINED_S3_PREFIX=${DR_LOCAL_S3_PRETRAINED_PREFIX}
      - PRETRAINED_S3_BUCKET=${DR_LOCAL_S3_BUCKET}
      - PRETRAINED_CHECKPOINT=${DR_LOCAL_S3_PRETRAINED_CHECKPOINT}
      - MODEL_S3_PREFIX=${DR_LOCAL_S3_MODEL_PREFIX}
      - MODEL_S3_BUCKET=${DR_LOCAL_S3_BUCKET}
      - HYPERPARAMETER_FILE_S3_KEY=${DR_LOCAL_S3_HYPERPARAMETERS_KEY}
      - MODELMETADATA_FILE_S3_KEY=${DR_LOCAL_S3_MODEL_METADATA_KEY}
      - CUDA_VISIBLE_DEVICES=${DR_SAGEMAKER_CUDA_DEVICES:-}
      - MAX_MEMORY_STEPS=${DR_TRAIN_MAX_STEPS_PER_ITERATION:-}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/sagemaker:/tmp/sagemaker"
  robomaker:
    image: awsdeepracercommunity/deepracer-robomaker:${DR_ROBOMAKER_IMAGE}
    command: ["${ROBOMAKER_COMMAND}"]
    ports:
      - "${DR_ROBOMAKER_TRAIN_PORT}:8080"
      - "${DR_ROBOMAKER_GUI_PORT}:5900"
    environment:
      - WORLD_NAME=${DR_WORLD_NAME}
      - SAGEMAKER_SHARED_S3_PREFIX=${DR_LOCAL_S3_MODEL_PREFIX}
      - SAGEMAKER_SHARED_S3_BUCKET=${DR_LOCAL_S3_BUCKET}
      - APP_REGION=${DR_AWS_APP_REGION}
      - S3_YAML_NAME=${DR_CURRENT_PARAMS_FILE}
      - KINESIS_VIDEO_STREAM_NAME=${DR_KINESIS_STREAM_NAME}
      - ENABLE_KINESIS=${DR_CAMERA_KVS_ENABLE}
      - ENABLE_GUI=${DR_GUI_ENABLE}
      - CUDA_VISIBLE_DEVICES=${DR_ROBOMAKER_CUDA_DEVICES:-}
      - MULTI_CONFIG
      - RTF_OVERRIDE=${DR_TRAIN_RTF:-}      
      - ROS_MASTER_URI=http://localhost:11311/
      - ROS_IP=127.0.0.1
      - GAZEBO_ARGS=${DR_GAZEBO_ARGS:-}
      - TELEGRAF_HOST=${DR_TELEGRAF_HOST:-}
      - TELEGRAF_PORT=${DR_TELEGRAF_PORT:-}
    init: true